### ISSUE TITLE
Pytorch implementation and Figure 3 Architecture

### ISSUE THREAD

**Issue by jpainam** [wenguanwang/Deep-Visual-Attention-Prediction#3]
Hi!
Please can you say which software you used to draw your Fig. 3. Architecture of our deep attention model?
And if there is any pytorch implementation of your paper to recommend.

Thank you.

**Comment by wenguanwang** [comment]
@jpainam 
Hi,
Thanks for your interest. I'm sorry but I don't know there exists any pytorch version of our model. 
I use visio to draw Fig. 3. : )

**Comment by jpainam** [comment]
Thank for your kind reply.
